config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users do
    resources :posts
  end

  get '/login'    => 'sessions#new', as: 'login'
  post '/login'   => 'sessions#create'
  get '/logout'   => 'sessions#destroy'
  get '/projects' => 'welcome#projects', as: 'projects'

end

app/models/concerns/post.rb
class Post < ActiveRecord::Base
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :project_url, presence: true
  validates :category, presence: true 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    if !current_user
      flash.notice = "Log in first."
      redirect_to login_path
    end
  end
  helper_method :authorize

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorize

  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.new(post_params)

    if @post.save
      redirect_to user_path(@user)
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])

    if @post.update(post_params)
      flash.notice = "Post updated."
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])

    @post.destroy
    flash.notice = "Post deleted"
    redirect_to user_path(@user)
  end

  private
    def post_params
      params.require(:post).permit(
        :title,
        :description,
        :project_url,
        :blog_url,
        :category
      )
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    if current_user
      redirect_to user_path(current_user)
    else
      @user = User.new
    end
  end

  def create
    user = User.find_by email_address: params[:email_address]

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash.notice = 'Incorrect email/password'
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize

  def show
    @user = User.find(params[:id])
    @posts = Post.all.where(:user_id == @user.id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @project_posts = Post.all.where(category: "project").order(created_at: :desc).limit(3);
  end

  def projects
    @project_posts = Post.all.where(category: "project").order(created_at: :desc);
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>

    <link href='https://fonts.googleapis.com/css?family=Dancing+Script:700|Cutive+Mono' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= flash.notice %>
    <%= yield %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/ScrollMagic.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/plugins/debug.addIndicators.min.js"></script>

  </body>

</html>

app/views/posts/_error.html.erb
<% if @post.errors.any? %>
  <h3><%= pluralize(@post.errors.count, "error") %> found.</h3>
  <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li>
        <%= message %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/posts/edit.html.erb
<% @title = "Anthony Ng | Edit post" %>

<h1>Edit Post</h1>

<%= render partial:"error" %>

<%= form_for @post, url: user_post_path do |f| %>
  <p>
    <%= f.text_field :title, placeholder: "title" %><br>
    <%= f.text_field :description, placeholder: "description" %><br>
    <%= f.text_field :project_url, placeholder: "link to project" %><br>
    <%= f.text_field :blog_url, placeholder: "link to blog" %><br>
    <%= f.text_field :category, placeholder: "category" %><br>
  </p>
  <p>
    <%= f.submit "Update Post" %>
  </p>
<% end %>

<%= link_to "<< Back", user_path(@user) %>

app/views/posts/new.html.erb
<% @title = "Anthony Ng | Create new post" %>

<h1>Create a new post</h1>

<%= render partial: "error" %>

<%= form_for([@user, @post]) do |f| %>
  <p>
    <%= f.text_field :title, placeholder: "title" %><br>
    <%= f.text_field :description, placeholder: "description" %><br>
    <%= f.text_field :project_url, placeholder: "link to project" %><br>
    <%= f.text_field :blog_url, placeholder: "link to blog" %><br>
    <%= f.text_field :category, placeholder: "category" %>
    <%= f.label "Current categories: Project" %>
  </p>
  <p>
    <%= f.submit "Create new post" %>
  </p>
<% end %>

<%= link_to "<< Back", user_path(@user) %>

app/views/users/show.html.erb
<h1><%= "Welcome Back, #{@user.fname}" %></h1>
<%= link_to "Logout", logout_path %><br>
<%= link_to "Create new post", new_user_post_path(@user) %>

<h2>All Posts</h2>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Project URL</th>
    <th>Blog URL</th>
    <th>Category</th>
  </tr>

  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.description %></td>
      <td><%= post.project_url %></td>
      <td><%= post.blog_url %></td>
      <td><%= post.category %></td>
      <td><%= link_to "Edit", edit_user_post_path(@user, post) %></td>
      <td><%= link_to "Delete", user_post_path(@user, post),
              method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
  <% end %>
</table>

app/views/welcome/_contacts.html.erb
<section>
  <div class="light-blue contacts">
    <h2 class="white-text">Contact Me</h2>
    <ul>
      <li class="white-text">newyork.anthonyng@gmail.com</li>
      <li><a href="https://github.com/newyork-anthonyng"
             target="_blank">Github</a>
      </li>
      <li><a href="https://www.linkedin.com/in/anthony-ng-02856056"
           target="_blank">Linkedin</a>
      </li>
    </ul>
  </div>
</section>

app/views/welcome/_header.html.erb
<section>
  <div class="light-blue header">
    <h1 class="white-text">Hey, I'm Anthony</h1>
      <p class="header-text white-text">I'm an aspiring web developer who loves</p>
      <p class="header-text white-text">
        <span class="amber-text" id="developing-text">developing</span>&nbsp; and &nbsp;
        <span class="amber-text" id="designing-text">designing</span>
      </p>
      <p class="header-text white-text">useful and practical web applications.</p>
    </div>
  </div>
</section>

<section class="parallaxParent" id="background-1"></section>

app/views/welcome/_project_post.html.erb
<% @project_posts.each do |project| %>
  <li>
    <p class="white-text">
      <%= project.title %> <span id="title-separator">»</span>
      <%= project.description %><br>
      <a href="<%= project.project_url %>" target="_blank" %>Link to Project</a>
      <% if project.blog_url != "" %>
        | <a href="<%= project.blog_url %>" target="_blank">Link to Blog</a>
      <% end %>
    </p>
  </li>
  <br>
<% end %>

app/views/welcome/_projects.html.erb
<section>
  <div class="light-blue projects">
    <h1 class="center-align white-text">Recent Projects</h1>
    <ul class="text">
      <%= render partial: "project_post" %>
      <%= link_to "(More Projects...)", projects_path %>
    </ul>
  </div>
</section>

<section class="parallaxParent" id="background-3"></section>

app/views/welcome/_skills.html.erb
<section>
  <div class="light-blue skills">
    <h1 class="right-align white-text">Skills</h1>

    <div class="row white-text">
      <div class="col s3">
        <!-- <img src="/assets/sketch.png"></img> -->
        <img src=<%= asset_path('sketch.png') %>></img>
      </div>
      <div class="col s3">
        JavaScript<br>
        Ruby<br>
        Rails<br>
        PostgreSQL<br>
      </div>
      <div class="col s3">
        MongoDB<br>
        Express<br>
        Angular<br>
        Node.js<br>
      </div>
      <div class="col s3">
        HTML<br>
        CSS<br>
        jQuery<br>
      </div>
    </div>
  </div>
</section>

<section class="parallaxParent" id="background-2"></section>

app/views/welcome/index.html.erb
<% @title = "Anthony Ng | Home" %>

<%= render partial: "header" %>
<%= render partial: "skills" %>
<%= render partial: "projects" %>
<%= render partial: "contacts" %>

app/views/welcome/projects.html.erb
<% @title = "Anthony Ng | Projects" %>

<div class="light-blue projects-main">
  <%= link_to "Home", root_path %>
  <h1 class="white-text">Projects</h1>
  <ul>
    <%= render partial: "project_post" %>
  </ul>
</div>